name: pincer

services:
  pincer:
    image: registry.digitalocean.com/anubis/pincer:${GIT_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        - GIT_TAG=${GIT_TAG:-latest}