# fly.toml app configuration file generated for pincer-proxy on 2024-03-14T17:38:58-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pincer-proxy'
primary_region = 'iad'

[build]
  dockerfile = './Dockerfile.server'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
