# fly.toml app configuration file generated for pincer-server on 2023-04-23T18:04:58-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pincer-server"
primary_region = "iad"

[build]
  dockerfile = "./Dockerfile.server"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
