name: Anubis Pincer CD/CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
  # Build Stage.
  # Will build the docker image, and push it
  # to the container registry.
  build-pincer:
    name: Build Pincer
    runs-on: ubuntu-latest
    environment: anubis
    steps:
      - uses: actions/checkout@v4
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log into DigitalOcean container registry
        run: doctl registry login
      - name: Build container image
        run: make build
      - name: Push image to registry
        run: make push
